language: cpp
sudo: required
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    packages:
    - cmake
services:
  - docker
before_install:
  - docker pull chraac/imagecompressenv
  - docker run -v ./:/opt/image_compress chraac/imagecompressenv
before_script:
  - cd /opt/image_compress
  - cd src/mozjpeg && cmake . && cd ../../
  - cmake .
script: 
  - make
branches:
  only:
  - master
